name: "veb-igrica-memorije"
services:
  frontend:
    build: ./veb-igrica-memorije
    container_name: memorije-front
    networks:
      - memorije-network
    volumes:
      - ./veb-igrica-memorije:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend: 
    build: ./backend
    container_name: memorije-back
    env_file:
      - ./env/backend.env
    networks:
      - memorije-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:5000"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
  database:
    image: mysql:latest
    container_name: memorije-db
    env_file:
      - ./env/mysql.env
    networks:
      - memorije-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/mysql-init:/docker-entrypoint-initdb.d/init.sql
      - ./database/mysql-cnf:/etc/mysql/conf.d/my-custom.cnf:ro
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost", "-u", "username", "--password=password"]
      interval: 10s
      timeout: 10s
      retries: 6
networks:
  memorije-network:
    driver: bridge
volumes:
  mysql-data: